# Generated by Django 5.2.6 on 2025-09-10 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='tipo',
            field=models.CharField(choices=[('laboratorio', 'Laboratorio'), ('salon', 'Salón Normal'), ('auditorio', 'Auditorio')], default='salon', max_length=20),
        ),
    ]
